services:
  mongodb:
    image: mongo:7
    container_name: ecommerce_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ecommerce_mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ecommerce_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  ecommerce_mongo_data:
